# ============================================================================ #
#                          Spawner Limiter Module                              #
# ============================================================================ #
# This module limits mob spawning from spawners to prevent lag.
# The module is enabled/disabled in the main config.yml.

spawn-delay-multiplier: 1.5

worlds: []
