# ClearLaggEnhanced Configuration
# Plugin Version: 1.3

# Debug mode
debug: false

# Entity Clearing Configuration
entity-clearing:
  enabled: true
  interval: 300  # Clear interval in seconds (5 minutes)
  protect-named-entities: true
  protect-tamed-entities: true
  
  # Worlds to clear entities in (empty list = all worlds)
  worlds: []
  
  # Entities to always clear (blacklist)
  blacklist:
    - "DROPPED_ITEM"
    - "ARROW"
    - "EXPERIENCE_ORB"
    - "PRIMED_TNT"
    - "FIREWORK"
    - "AREA_EFFECT_CLOUD"
    - "ZOMBIE"
    - "SKELETON"
    - "CREEPER"
    - "SPIDER"
    - "ENDERMAN"
    - "SLIME"
    - "MAGMA_CUBE"
    - "WITCH"
    - "PHANTOM"
    - "DROWNED"
    - "HOGLIN"
    - "PIGLIN"
    - "ZOMBIFIED_PIGLIN"
  
  # Entities to never clear (whitelist/protected)
  whitelist:
    - "PLAYER"
    - "VILLAGER"
    - "IRON_GOLEM"
    - "SNOW_GOLEM"
    - "ARMOR_STAND"
    - "ITEM_FRAME"
    - "PAINTING"
    - "MINECART"
    - "BOAT"

# Lag Prevention Modules
lag-prevention:
  # Mob Limiter
  mob-limiter:
    enabled: true
    max-mobs-per-chunk: 50
    
  # Redstone Limiter
  redstone-limiter:
    enabled: true
    max-redstone-per-chunk: 100
    
  # Hopper Limiter
  hopper-limiter:
    enabled: true
    transfer-cooldown: 8  # ticks
    
  # Spawner Limiter
  spawner-limiter:
    enabled: true
    spawn-delay-multiplier: 1.5
  
  # Misc (non-mob) entity limiter
  misc-entity-limiter:
    enabled: true

    # Entities to manage and their per-chunk caps (-1 or missing = unlimited)
    limits-per-chunk:
      ARMOR_STAND: 5
      BOAT: 5
      CHEST_BOAT: 5
      MINECART: 5
      ITEM_FRAME: 5
      GLOW_ITEM_FRAME: 5
      PAINTING: 5

    protect:
      named: true
      tags:
        - "CLE_PROTECTED"

    sweep:
      interval-ticks: 100
      max-chunks-per-tick: 20

    notify:
      admins-permission: "CLE.admin"
      throttle-seconds: 60

    # Worlds allowlist (empty = all worlds)
    worlds: []

# Chunk Finder Configuration
chunk-finder:
  radius: 10  # chunks around player to scan
  entity-threshold: 50  # entities per chunk to consider "laggy"

# Notification Settings
notifications:
  # Broadcast times (seconds before clear)
  broadcast-times: [60, 30, 10, 5]
  
  # Notification type: CHAT, ACTION_BAR, or TITLE
  type: "ACTION_BAR"
  
  # Sound settings
  sound:
    enabled: true
    name: "BLOCK_NOTE_BLOCK_PLING"
    volume: 1.0
    pitch: 1.2

# Performance Monitoring
performance:
  update-interval: 20  # ticks between updates
  
# Database Settings
database:
  type: "sqlite"  # sqlite or mysql
  file: "clearlagg.db"
  
  # MySQL settings (if using mysql)
  mysql:
    host: "localhost"
    port: 3306
    database: "clearlagg"
    username: "root"
    password: "password"
    ssl: false
