# ClearLaggEnhanced Configuration
# The ultimate performance management plugin for Minecraft servers


# General plugin settings
general:
  # Plugin language (en, es, fr, de, etc.)
  language: "en"
  
  # Enable debug mode for troubleshooting
  debug-mode: false
  
  # Enable verbose console logging
  verbose-logging: false

# bStats metrics settings
metrics:
  # Enable bStats metrics (helps development)
  enabled: true

# Global performance settings
performance:
  # Number of async threads for background tasks
  async-threads: 2
  
  # Target server TPS
  max-ticks-per-second: 20
  
  # TPS threshold for 'low performance' warnings
  low-tps-threshold: 18.0
  
  # TPS threshold for 'critical performance' actions
  critical-tps-threshold: 15.0