name: ClearLaggEnhanced
version: '${project.version}'
main: org.busybee.clearlaggenhanced.ClearLaggEnhanced
description: 'The ultimate performance management plugin for Minecraft servers'
author: djtmk
api-version: '1.21'
folia-supported: true

softdepend:
  - ProtocolLib
  - Vault
  - VaultUnlocked
  - PlaceholderAPI

commands:
  clearlagg:
    description: Main ClearLaggEnhanced command
    usage: /<command> [subcommand] [args...]
    aliases: [cle, clearlag, lagg]

permissions:
  clearlaggenhanced.*:
    description: Access to all ClearLaggEnhanced features
    default: op
    children:
      clearlaggenhanced.admin: true
      clearlaggenhanced.check: true
      clearlaggenhanced.reload: true
      
  clearlaggenhanced.admin:
    description: Full administrative access
    default: op
    children:
      clearlaggenhanced.clear: true
      clearlaggenhanced.killmobs: true
      clearlaggenhanced.unloadchunks: true
      clearlaggenhanced.gc: true
      clearlaggenhanced.config: true
      clearlaggenhanced.profile: true
      clearlaggenhanced.menu: true
      
  clearlaggenhanced.clear:
    description: Clear entities manually
    default: op
    
  clearlaggenhanced.killmobs:
    description: Kill mobs with advanced filtering
    default: op
    
  clearlaggenhanced.unloadchunks:
    description: Unload chunks manually
    default: op
    
  clearlaggenhanced.check:
    description: View server performance diagnostics
    default: op
    
  clearlaggenhanced.tps:
    description: View TPS and MSPT information
    default: op
    
  clearlaggenhanced.memory:
    description: View memory usage information
    default: op
    
  clearlaggenhanced.gc:
    description: Force garbage collection
    default: op
    
  clearlaggenhanced.reload:
    description: Reload plugin configuration
    default: op
    
  clearlaggenhanced.config:
    description: Modify configuration in-game
    default: op
    
  clearlaggenhanced.profile:
    description: Access profiling commands
    default: op
    
  clearlaggenhanced.menu:
    description: Access the GUI control panel
    default: op