# ============================================================================ #
#                        ModernShowcase Integration                            #
# ============================================================================ #
# This module provides integration with ModernShowcase.
# The module is enabled/disabled in the main config.yml.
#
# There are no additional settings for this module.
