limits-per-chunk:
  ARMOR_STAND: 50
  BOAT: 4
  CHEST_BOAT: 4
  MINECART: 4
  ITEM_FRAME: 200
  GLOW_ITEM_FRAME: 200
  LEASH_HITCH: -1
  PAINTING: 200
  ITEM_DISPLAY: 200
  MINECART_CHEST: 4
  MINECART_HOPPER: 4
  MINECART_FURNACE: 4

protect:
  named: true
  citizens: true
  tags:
    - CLE_PROTECTED

sweep:
  interval-ticks: 100
  max-chunks-per-tick: 20

notify:
  admins-permission: CLE.admin
  throttle-seconds: 60

worlds: []
enabled: true
